### ISSUE TITLE
Slider width/height configuration doesn't work

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-plugin-slider#1]
Seems like these values are not used at all.
![2016-02-29_14-25-01](https://cloud.githubusercontent.com/assets/7892851/13389219/5575e570-def0-11e5-9594-2296b4f980bb.png)

**Comment by semchishinv** [comment]
Done.
Plugin Configuration (Dimensions part) moved into Slider Blocks Configuration it self  
![image](https://user-images.githubusercontent.com/30542757/36827617-de0a70b6-1d3e-11e8-9e4b-ca91c8124dea.png)
