### ISSUE TITLE
Subrion 4.2 - Cannot add sliders

### ISSUE THREAD

**Issue by CKENT0369** [intelliants/subrion-plugin-slider#14]
After my previous ticket about blank page, I downloaded the version here on GIT, Blank page goes away however, I cannot add sliders. I add a slider block, go back to sliders and try to add a slider. It says "You should create at least one slider block first" will not let me create slider. 

Further it appears the options I select for the slider on the create block page do not save.

**Comment by vbezruchkin** [comment]
Related to #13. Closing as duplicate. Thanks for reporting.
