### ISSUE TITLE
Changes on plugin settings does not take effect 

### ISSUE THREAD

**Issue by chupetoide** [intelliants/subrion-plugin-slider#3]
Hi, I am trying the latest plugin version with Subrion 4.1.3.11 and when I change any setting (i.e. scroll duration or direction) from the configuration form it doesn't change anything. I am looking on the html output and on the database (table slider_block_option) but nothing changes. Let's say we set 1500 milliseconds as the scroll duration. I save the form, logout the admin panel and then login again. I can see this value on the form but on the database it has the old one ( 500 ms ).

Is it a bug or I am doing it wrong?

**Comment by semchishinv** [comment]
Fixed.
